/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/login": {
    /** User Login */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Login Successful */
        200: {
          content: {
            "application/json": {
              statusCode?: number;
              success?: boolean;
              message?: string;
              data?: components["schemas"]["LoginData"];
            };
          };
        };
      };
    };
  };
  "/api/v1/auth/refresh-token": {
    /** Refresh Access Token */
    post: {
      requestBody: {
        content: {
          "application/json": {
            refreshToken: string;
          };
        };
      };
      responses: {
        /** @description Token rotated successfully */
        200: {
          content: {
            "application/json": {
              statusCode?: number;
              success?: boolean;
              data?: {
                accessToken?: string;
                refreshToken?: string;
              };
            };
          };
        };
      };
    };
  };
  "/api/v1/finance/dashboard": {
    /** Get Company Finance Overview */
    get: {
      responses: {
        /** @description Financial metrics */
        200: {
          content: {
            "application/json": {
              statusCode?: number;
              success?: boolean;
              data?: components["schemas"]["FinanceDashboard"];
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      _id?: string;
      name?: string;
      email?: string;
      /** @enum {string} */
      role?: "SUPER_ADMIN" | "COMPANY_ADMIN" | "HR" | "MANAGER" | "EMPLOYEE";
      companyId?: string;
      permissions?: string[];
    };
    LoginData: {
      user?: components["schemas"]["User"];
      accessToken?: string;
      refreshToken?: string;
    };
    FinanceDashboard: {
      period?: string;
      totalRevenue?: number;
      totalExpense?: number;
      netProfit?: number;
      marginPercentage?: number;
      isOverspending?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
